Update container files
Make them work with Docker and Podman.

Also updated for Rocky Linux 8 instead of CentOS 6 now that the kit has
been updated to work with EGen v1.14.0.

diff --git a/container/build-database b/container/build-database
--- a/container/build-database
+++ b/container/build-database
@@ -1,12 +1,17 @@
 #!/bin/sh
 
-# Build a Docker image with the DBT-5 database created.
+# Build a container image with the DBT-5 database created.
 
-which docker > /dev/null 2>&1
+ENGINE="podman"
+which podman > /dev/null 2>&1
 if [ $? -ne 0 ]; then
-	echo "docker not in path"
-	exit 1
+	which $ENGINE > /dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		echo "podman nor docker in path"
+		exit 1
+	fi
 fi
+
 
 SCALE=500
 DBMS="pgsql"
@@ -34,20 +39,25 @@ echo "Using PostgreSQL Major Version $PGVERSION"
 
 TOPDIR=`dirname $0`
 
-# Use the return code from `docker inspect` to determine if the docker image
-# needs to be created.
-docker inspect dbt5-base > /dev/null
+# Use the return code from `$ENGINE inspect` to determine if the container
+# image needs to be created.
+$ENGINE inspect dbt5-base > /dev/null
 if [ $? -ne 0 ]; then
 	${TOPDIR}/prepare-image || exit 1
 fi
 
+if [ "$ENGINE" = "podman" ]; then
+	PODMANARGS="--isolation=chroot"
+fi
+
 TOPDIR="${TOPDIR}/.."
-docker build -t dbt5-database-${DBMS}-${SCALE}s \
+$ENGINE build -t dbt5-database-${DBMS}-${SCALE}s \
+		$PODMANARGS \
 		--build-arg PGVERSION=$PGVERSION \
 		--build-arg DBMS=$DBMS \
 		--build-arg SCALE=$SCALE \
 		--shm-size=256m \
-		-f Dockerfile.database $TOPDIR
+		-f Containerfile.database $TOPDIR
 if [ $? -ne 0 ]; then
 	echo "usage: $0 [SCALE [DBMS [DBMSVER]]]"
 	echo
diff --git a/container/build-driver b/container/build-driver
--- a/container/build-driver
+++ b/container/build-driver
@@ -1,14 +1,18 @@
 #!/bin/sh
 
-# Build a Docker image with the DBT-5 Brokerage House.
-
-which docker > /dev/null 2>&1
-if [ $? -ne 0 ]; then
-	echo "docker not in path"
-	exit 1
-fi
+# Build a Container image with the DBT-5 Brokerage House.
 
 PGVERSION=14.2
+
+ENGINE="podman"
+which podman > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+	which $ENGINE > /dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		echo "podman nor docker in path"
+		exit 1
+	fi
+fi
 
 if [ $# -ge 1 ]; then
 	PGVERSION=$1
@@ -24,17 +28,22 @@ echo "Using PostgreSQL Major Version $PGVERSION"
 
 TOPDIR=`dirname $0`
 
-# Use the return code from `docker inspect` to determine if the docker image
+# Use the return code from `$ENGINE inspect` to determine if the $ENGINE image
 # needs to be created.
-docker inspect dbt5-base > /dev/null
+$ENGINE inspect dbt5-base > /dev/null
 if [ $? -ne 0 ]; then
 	${TOPDIR}/prepare-image || exit 1
 fi
 
+if [ "$ENGINE" = "podman" ]; then
+	PODMANARGS="--isolation=chroot"
+fi
+
 TOPDIR="${TOPDIR}/.."
-docker build -t dbt5-driver \
+$ENGINE build -t dbt5-driver \
+		$PODMANARGS \
 		--build-arg PGVERSION=$PGVERSION \
-		-f Dockerfile.common $TOPDIR
+		-f Containerfile.common $TOPDIR
 if [ $? -ne 0 ]; then
 	echo "usage: $0 [DBMSVER]"
 	echo
diff --git a/container/start-database b/container/start-database
--- a/container/start-database
+++ b/container/start-database
@@ -2,10 +2,14 @@
 
 # Start the DBT-5 PostgreSQL database.
 
-which docker > /dev/null 2>&1
+ENGINE="podman"
+which podman > /dev/null 2>&1
 if [ $? -ne 0 ]; then
-	echo "docker not in path"
-	exit 1
+	which $ENGINE > /dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		echo "podman nor docker in path"
+		exit 1
+	fi
 fi
 
 SCALE=500
@@ -19,21 +23,27 @@ if [ $# -ge 2 ]; then
 	DBMS=$2
 fi
 
-DOCKERDIR=`dirname $0`
-DOCKER_TAG="dbt5-database-${DBMS}-${SCALE}s"
-DOCKER_NAME="dbt5-database-${DBMS}-${SCALE}s-0"
+CONTAINERDIR=$(dirname $0)
+CONTAINER_TAG="dbt5-database-${DBMS}-${SCALE}s"
+CONTAINER_NAME="dbt5-database-${DBMS}-${SCALE}s-0"
 
-# Use the return code from `docker inspect` to determine if the docker image
+# Use the return code from `$ENGINE inspect` to determine if the container image
 # needs to be created.
-docker inspect $DOCKER_TAG > /dev/null
+$ENGINE inspect $CONTAINER_TAG > /dev/null
 if [ $? -ne 0 ]; then
-	${DOCKERDIR}/build-database $SCALE $DBMS || exit 1
+	${CONTAINERDIR}/build-database $SCALE $DBMS || exit 1
+fi
+
+if [ "$ENGINE" = "podman" ]; then
+	PODMANARGS="--network=podman"
 fi
 
 if [ "x$DBMS" = "xpgsql" ]; then
 	PGDATA="/opt/pgdata"
-	docker run -d --rm -u postgres:postgres --name $DOCKER_NAME -p 5432:5432 \
-			$DOCKER_TAG postgres -D $PGDATA \
+	$ENGINE run \
+			$PODMANARGS \
+			-d --rm -u postgres:postgres --name $CONTAINER_NAME \
+			-p 5432:5432 $CONTAINER_TAG postgres -D $PGDATA \
 			-c client_encoding='SQL_ASCII' \
 			-c listen_addresses='*' \
 			-c unix_socket_directories='/tmp'
@@ -51,9 +61,9 @@ fi
 
 which jq > /dev/null 2>&1
 if [ $? -eq 0 ]; then
-	IPADDRESS=`docker inspect $DOCKER_NAME | jq -r '.[0].NetworkSettings.IPAddress'`
+	IPADDRESS=$($ENGINE inspect $CONTAINER_NAME | jq -r '.[0].NetworkSettings.IPAddress')
 	echo "IP Address: $IPADDRESS"
-	echo "${DOCKERDIR}/start-client $IPADDRESS $DBMS"
+	echo "${CONTAINERDIR}/start-client $IPADDRESS $DBMS"
 	if [ "x$DBMS" = "xpgsql" ]; then
 		echo "psql -h $IPADDRESS dbt5 postgres"
 	fi
